# Generated by Django 5.1 on 2024-09-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmeruser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='farmeruser',
            name='otp_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
