# Generated by Django 5.1 on 2024-09-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_farmeruser_otp_farmeruser_otp_sent_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmeruser',
            name='user_farmsize',
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='language_preference',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='user_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
