# Generated by Django 5.1 on 2024-09-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_farmeruser_user_farmsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmeruser',
            name='user_aadhaarnumber',
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='user_phonenumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
