name: farmcare
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  get: 4.6.6
  hive: 2.2.3
  hive_flutter: 1.1.0
  dio: 5.6.0
  get_storage: 2.1.1
  flutter_easyloading: 3.0.5
  path_provider: 2.1.4
  intl: 0.19.0
  equatable: 2.0.5
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

